// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCp5-8BabXEpXf9OafwZqXI1fDo8JGMysg',
    appId: '1:456980033495:web:66be07cd5792abb9f0e592',
    messagingSenderId: '456980033495',
    projectId: 'nose-a8241',
    authDomain: 'nose-a8241.firebaseapp.com',
    storageBucket: 'nose-a8241.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAC2cXI6TXwcwIlKTrMbVw8S-bPyvZ_nTY',
    appId: '1:456980033495:android:4356049ab199e88ef0e592',
    messagingSenderId: '456980033495',
    projectId: 'nose-a8241',
    storageBucket: 'nose-a8241.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyCzKkWvI5Sf-QFQzdK_GghTCJidPyc4g',
    appId: '1:456980033495:ios:103b9cc4dbe9ad83f0e592',
    messagingSenderId: '456980033495',
    projectId: 'nose-a8241',
    storageBucket: 'nose-a8241.firebasestorage.app',
    iosBundleId: 'com.example.nose',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAyCzKkWvI5Sf-QFQzdK_GghTCJidPyc4g',
    appId: '1:456980033495:ios:103b9cc4dbe9ad83f0e592',
    messagingSenderId: '456980033495',
    projectId: 'nose-a8241',
    storageBucket: 'nose-a8241.firebasestorage.app',
    iosBundleId: 'com.example.nose',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCp5-8BabXEpXf9OafwZqXI1fDo8JGMysg',
    appId: '1:456980033495:web:a65ee86ec968008df0e592',
    messagingSenderId: '456980033495',
    projectId: 'nose-a8241',
    authDomain: 'nose-a8241.firebaseapp.com',
    storageBucket: 'nose-a8241.firebasestorage.app',
  );
}
